sudo: required

services:
  - docker

before_install:
  - docker build -t sam35/react-test -f ./client/Dockerfile.dev ./client

# primary test running section, any scripts exit with non zero status code, build fails
script:
  - docker run -e CI=true sam35/react-test npm test -- --watchAll=false

after_success:
  # need to do a build for each of our sub dirs/services
  - docker build -t sam35/multi-client ./client
  - docker build -t sam35/multi-nginx ./nginx
  - docker build -t sam35/multi-server ./server
  - docker build -t sam35/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take images and push to dockerhub
  - docker push sam35/multi-client
  - docker push sam35/multi-nginx
  - docker push sam35/multi-server
  - docker push sam35/multi-worker

  